### Updates an existing patient entity
PUT http://localhost:4000/patients/id/update
Content-Type: application/json

{
  "name": "John Doe UPDATED",
  "email": "john.doe@example.com",
  "address": "123 main street",
  "dateOfBirth": "1995-09-09"
}

###